-- CreateTable
CREATE TABLE "Contact" (
    "id" SERIAL NOT NULL,
    "contactId" INTEGER NOT NULL,
    "userId" INTEGER,
    "givenName" TEXT,
    "title" TEXT,
    "middleName" TEXT,
    "preferredName" TEXT,
    "surname" TEXT,
    "emailAddress" TEXT,
    "emailAddressAlternative" TEXT,
    "sex" TEXT,
    "dob" TEXT,
    "historicClientId" TEXT,
    "optionalId" TEXT,
    "usi" TEXT,
    "usiVerified" BOOLEAN,
    "usiExemption" BOOLEAN,
    "vsn" TEXT,
    "lui" TEXT,
    "workReadyParticipantNumber" TEXT,
    "saceStudentId" TEXT,
    "position" TEXT,
    "section" TEXT,
    "division" TEXT,
    "organisation" TEXT,
    "orgId" INTEGER,
    "orgIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "buildingName" TEXT,
    "unitNo" TEXT,
    "streetNo" TEXT,
    "streetName" TEXT,
    "poBox" TEXT,
    "address1" TEXT,
    "address2" TEXT,
    "city" TEXT,
    "state" TEXT,
    "postcode" TEXT,
    "countryId" INTEGER,
    "country" TEXT,
    "sBuildingName" TEXT,
    "sUnitNo" TEXT,
    "sStreetNo" TEXT,
    "sStreetName" TEXT,
    "sPoBox" TEXT,
    "sAddress1" TEXT,
    "sAddress2" TEXT,
    "sCity" TEXT,
    "sState" TEXT,
    "sPostcode" TEXT,
    "sCountryId" INTEGER,
    "sCountry" TEXT,
    "phone" TEXT,
    "mobilePhone" TEXT,
    "workPhone" TEXT,
    "fax" TEXT,
    "sourceCodeId" INTEGER,
    "source" TEXT,
    "comment" TEXT,
    "website" TEXT,
    "citizenStatusId" INTEGER,
    "citizenStatusName" TEXT,
    "fkResidencyStatusId" INTEGER,
    "fkResidencyStatusName" TEXT,
    "countryOfBirthId" INTEGER,
    "countryOfBirthName" TEXT,
    "cityOfBirth" TEXT,
    "countryOfCitizenId" INTEGER,
    "countryOfCitizenName" TEXT,
    "indigenousStatusId" INTEGER,
    "indigenousStatusName" TEXT,
    "mainLanguageId" INTEGER,
    "mainLanguageName" TEXT,
    "englishProficiencyId" INTEGER,
    "englishAssistanceFlag" BOOLEAN,
    "highestSchoolLevelId" INTEGER,
    "highestSchoolLevelYear" TEXT,
    "currentSchoolLevel" INTEGER,
    "atSchoolFlag" BOOLEAN,
    "atSchoolName" TEXT,
    "priorEducationIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "priorEducationNames" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "priorEducationStatus" BOOLEAN,
    "disabilityFlag" BOOLEAN,
    "disabilityTypeIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "disabilityTypeNames" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "labourForceId" INTEGER,
    "labourForceName" TEXT,
    "anzscoCode" TEXT,
    "anzsicCode" TEXT,
    "ielts" TEXT,
    "surveyContactStatusCode" TEXT,
    "emergencyContact" TEXT,
    "emergencyContactRelation" TEXT,
    "emergencyContactPhone" TEXT,
    "employerContactId" INTEGER,
    "payerContactId" INTEGER,
    "supervisorContactId" INTEGER,
    "coachContactId" INTEGER,
    "agentContactId" INTEGER,
    "contactRoleId" INTEGER,
    "yearOfArrivalAus" TEXT,
    "customFieldAdditionalSupport" TEXT,
    "customFieldAdditionalSupportRequired" TEXT,
    "customFieldParentGuardianContactNumber" TEXT,
    "customFieldEmployer" TEXT,
    "customFieldJobTitle" TEXT,
    "customFieldCJobTitle" TEXT,
    "customFieldCombinedDeclaration" TEXT,
    "customFieldDeclarations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "customFieldParentGuardianEmail" TEXT,
    "customFieldCanPerformCpr2Mins" TEXT,
    "customFieldPrecourseWork" TEXT,
    "customFieldMarketingPermission" TEXT,
    "customFieldParentGuardianFullName" TEXT,
    "customFieldUsiPermission" TEXT,
    "customFieldPreviousJobTitles" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "customFieldPreviousJobTitlesOther" TEXT,
    "customFieldPreviousCerts" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "customFieldParentGuardianRelationship" TEXT,
    "customFieldWellbeingRequirements" TEXT,
    "lastUpdated" TEXT,
    "contactEntryDate" TEXT,
    "contactActive" BOOLEAN DEFAULT true,
    "photo" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Contact_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Contact_contactId_key" ON "Contact"("contactId");

-- CreateIndex
CREATE INDEX "Contact_emailAddress_idx" ON "Contact"("emailAddress");

-- CreateIndex
CREATE INDEX "Contact_surname_givenName_idx" ON "Contact"("surname", "givenName");
