export const countryOptions = [
  { value: "4216", label: "Abu Dhabi" },
  { value: "3207", label: "Acarnania" },
  { value: "5202", label: "Aceh" },
  { value: "3207", label: "Achaea" },
  { value: "4215", label: "Adana" },
  { value: "1601", label: "Adelie Land (France)" },
  { value: "4217", label: "Aden" },
  { value: "3207", label: "Aegean Islands" },
  { value: "3207", label: "Aegean Macedonia" },
  { value: "7201", label: "Afghanestan" },
  { value: "7201", label: "Afghanistan" },
  { value: "0918", label: "Africa" },
  { value: "3207", label: "Aghion Oros" },
  { value: "3204", label: "Agram" },
  { value: "1501", label: "Aitutaki Island" },
  { value: "2408", label: "Aland" },
  { value: "2408", label: "Aland Islands" },
  { value: "8104", label: "Alaska" },
  { value: "3201", label: "Albania" },
  { value: "8102", label: "Alberta" },
  { value: "2107", label: "Alderney" },
  { value: "4214", label: "Aleppo" },
  { value: "4102", label: "Alexandria" },
  { value: "4101", label: "Algeria" },
  { value: "4101", label: "Algerie" },
  { value: "4108", label: "Alhucemas" },
  { value: "5202", label: "Ambon" },
  { value: "8104", label: "America" },
  { value: "1506", label: "American Samoa" },
  { value: "8000", label: "Americas" },
  { value: "4206", label: "Amman" },
  { value: "5105", label: "An Giang" },
  { value: "4215", label: "Anatolia" },
  { value: "7103", label: "Andaman Island" },
  { value: "7103", label: "Andhra Pradesh" },
  { value: "3101", label: "Andorra" },
  { value: "2102", label: "Angleterre" },
  { value: "9201", label: "Angola" },
  { value: "8401", label: "Anguilla" },
  { value: "2304", label: "Anhalt" },
  { value: "4215", label: "Ankara" },
  { value: "1600", label: "Antarctica" },
  { value: "8402", label: "Antigua" },
  { value: "8402", label: "Antigua and Barbuda" },
  { value: "2104", label: "Antrim" },
  { value: "1304", label: "Api Island" },
  { value: "3104", label: "Apulia" },
  { value: "4213", label: "Arabia" },
  { value: "3207", label: "Arcadia" },
  { value: "8201", label: "Argentina" },
  { value: "1602", label: "Argentinian Antarctic Territory" },
  { value: "2104", label: "Armagh" },
  { value: "7202", label: "Armenia" },
  { value: "8403", label: "Aruba" },
  { value: "4105", label: "As Sudan" },
  { value: "9222", label: "Ascension" },
  { value: "0917", label: "Asia" },
  { value: "4215", label: "Asia Minor" },
  { value: "7103", label: "Assam" },
  { value: "4200", label: "Assyria" },
  { value: "4203", label: "Assyria Iran" },
  { value: "4204", label: "Assyria Iraq" },
  { value: "4102", label: "Aswan" },
  { value: "0001", label: "At Sea" },
  { value: "1501", label: "Atiu Island" },
  { value: "3207", label: "Attica" },
  { value: "1101", label: "Australia" },
  { value: "1100", label: "Australia (includes External Territories)" },
  { value: "1603", label: "Australian Antarctic Territory" },
  { value: "1101", label: "Australian Capital Territory" },
  { value: "1199", label: "Australian External Territories, nec" },
  { value: "2301", label: "Austria" },
  { value: "4215", label: "Aydin" },
  { value: "9225", label: "Azania" },
  { value: "7203", label: "Azerbaidzhan" },
  { value: "7203", label: "Azerbaijan" },
  { value: "3106", label: "Azores" },
  { value: "2304", label: "Baden Wurttemberg" },
  { value: "8404", label: "Bahamas" },
  { value: "4201", label: "Bahrain" },
  { value: "1599", label: "Baker Island" },
  { value: "3108", label: "Balearic Islands" },
  { value: "3203", label: "Balgarija" },
  { value: "5202", label: "Bali" },
  { value: "3300", label: "Baltic States" },
  { value: "1402", label: "Banaba" },
  { value: "3000", label: "Banat" },
  { value: "5202", label: "Banda Islands" },
  { value: "5202", label: "Bangay" },
  { value: "5202", label: "Banggai Islands" },
  { value: "7101", label: "Bangladesh" },
  { value: "8405", label: "Barbados" },
  { value: "4100", label: "Barbary" },
  { value: "8402", label: "Barbuda" },
  { value: "3108", label: "Basque" },
  { value: "4204", label: "Basra" },
  { value: "9211", label: "Basutoland" },
  { value: "5204", label: "Bataan" },
  { value: "5202", label: "Batavia" },
  { value: "1101", label: "Bathurst Island" },
  { value: "2304", label: "Bavaria" },
  { value: "4208", label: "Beirut" },
  { value: "4202", label: "Beit Jala" },
  { value: "3301", label: "Belarus" },
  { value: "2104", label: "Belfast" },
  { value: "9108", label: "Belgian Congo" },
  { value: "2302", label: "Belgie" },
  { value: "2302", label: "Belgium" },
  { value: "3215", label: "Belgrade" },
  { value: "8301", label: "Belize" },
  { value: "3301", label: "Belorussia" },
  { value: "9101", label: "Benin" },
  { value: "2304", label: "Berlin" },
  { value: "8101", label: "Bermuda" },
  { value: "3000", label: "Bessarabia" },
  { value: "7103", label: "Bharat" },
  { value: "7102", label: "Bhutan" },
  { value: "5202", label: "Biak" },
  { value: "5202", label: "Billiton Island" },
  { value: "5202", label: "Bintan Island" },
  { value: "5202", label: "Bintang Island" },
  { value: "9112", label: "Bioko" },
  { value: "3302", label: "Bohemia" },
  { value: "3302", label: "Bohmen ud Mahren" },
  { value: "8202", label: "Bolivia" },
  { value: "8202", label: "Bolivia, Plurinational State of" },
  { value: "8433", label: "Bonaire" },
  { value: "8433", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "6201", label: "Bonin Islands" },
  { value: "0001", label: "Born at Sea" },
  { value: "5200", label: "Borneo" },
  { value: "3202", label: "Bosna" },
  { value: "3202", label: "Bosnia" },
  { value: "3202", label: "Bosnia and Herzegovina" },
  { value: "3202", label: "Bosnija" },
  { value: "9202", label: "Botswana" },
  { value: "1302", label: "Bougainville" },
  { value: "8203", label: "Brasil" },
  { value: "8203", label: "Brazil" },
  { value: "2304", label: "BRD" },
  { value: "2304", label: "Bremen" },
  { value: "2100", label: "Britain" },
  { value: "1604", label: "British Antarctic Territory" },
  { value: "5203", label: "British Borneo" },
  { value: "5101", label: "British Burma" },
  { value: "8102", label: "British Columbia" },
  { value: "9200", label: "British East Africa" },
  { value: "8211", label: "British Guiana" },
  { value: "8301", label: "British Honduras" },
  { value: "7103", label: "British India" },
  { value: "9299", label: "British Indian Ocean Territory" },
  { value: "2100", label: "British Isles" },
  { value: "5203", label: "British Malaya" },
  { value: "1303", label: "British Solomon Islands Protectorate" },
  { value: "9224", label: "British Somaliland" },
  { value: "8427", label: "British Virgin Islands" },
  { value: "9100", label: "British West Africa" },
  { value: "8400", label: "British West Indies" },
  { value: "5201", label: "Brunei" },
  { value: "5201", label: "Brunei Darussalam" },
  { value: "3000", label: "Bukovina" },
  { value: "3203", label: "Bulgaria" },
  { value: "9102", label: "Burkina Faso" },
  { value: "5101", label: "Burma" },
  { value: "5101", label: "Burma (Myanmar)" },
  { value: "5101", label: "Burma (Republic of the Union of Myanmar)" },
  { value: "4215", label: "Bursa" },
  { value: "9203", label: "Burundi" },
  { value: "3301", label: "Byelorussia" },
  { value: "9201", label: "Cabinda" },
  { value: "4102", label: "Cairo" },
  { value: "3104", label: "Calabria" },
  { value: "8104", label: "California" },
  { value: "5102", label: "Cambodia" },
  { value: "9103", label: "Cameroon" },
  { value: "9103", label: "Cameroun" },
  { value: "3104", label: "Campania" },
  { value: "8102", label: "Canada" },
  { value: "3108", label: "Canary Islands" },
  { value: "1402", label: "Canton Island" },
  { value: "9104", label: "Cape Verde" },
  { value: "3104", label: "Capri" },
  { value: "3308", label: "Carelia" },
  { value: "8400", label: "Caribbean" },
  { value: "1402", label: "Caroline Island" },
  { value: "7200", label: "Caucasus" },
  { value: "2201", label: "Cavan" },
  { value: "8406", label: "Cayman Islands" },
  { value: "5202", label: "Celebes" },
  { value: "9100", label: "Central Africa" },
  { value: "9105", label: "Central African Empire" },
  { value: "9105", label: "Central African Republic" },
  { value: "8300", label: "Central America" },
  { value: "9100", label: "Central and West Africa" },
  { value: "7200", label: "Central Asia" },
  { value: "3300", label: "Ceskoslovensko" },
  { value: "4108", label: "Ceuta" },
  { value: "7107", label: "Ceylon" },
  { value: "2311", label: "CH" },
  { value: "9106", label: "Chad" },
  { value: "4108", label: "Chafarinas" },
  { value: "3207", label: "Chalkidiki" },
  { value: "7103", label: "Chandigarh" },
  { value: "2100", label: "Channel Islands" },
  { value: "1201", label: "Chatham Islands" },
  { value: "3204", label: "Cherso" },
  { value: "8204", label: "Chile" },
  { value: "1605", label: "Chilean Antarctic Territory" },
  { value: "6101", label: "China" },
  { value: "6101", label: "China (excludes SARs and Taiwan)" },
  { value: "6100", label: "Chinese Asia (includes Mongolia)" },
  { value: "3207", label: "Chios" },
  { value: "6202", label: "Chosan" },
  { value: "6200", label: "Chosen" },
  { value: "6202", label: "Choson" },
  { value: "1101", label: "Christmas Island" },
  { value: "1101", label: "Christmas Island (Australia)" },
  { value: "1101", label: "Christmas Island (Indian Ocean)" },
  { value: "1402", label: "Christmas Island (Pacific Ocean)" },
  { value: "1101", label: "Cocos (Keeling) Islands" },
  { value: "1101", label: "Cocos Island" },
  { value: "8205", label: "Colombia" },
  { value: "9204", label: "Comoro Island" },
  { value: "9204", label: "Comoros" },
  { value: "9107", label: "Congo" },
  { value: "9108", label: "Congo, Democratic Republic of" },
  { value: "9107", label: "Congo, People's Republic of" },
  { value: "9107", label: "Congo, Republic of" },
  { value: "1501", label: "Cook Islands" },
  { value: "1199", label: "Coral Sea Islands" },
  { value: "3207", label: "Corfu" },
  { value: "2201", label: "Cork" },
  { value: "2303", label: "Corsica" },
  { value: "4215", label: "Corum" },
  { value: "8302", label: "Costa Rica" },
  { value: "9111", label: "Cote d'Ivoire" },
  { value: "3207", label: "Crete" },
  { value: "3312", label: "Crimea" },
  { value: "3211", label: "Crisana" },
  { value: "3204", label: "Croatia" },
  { value: "3300", label: "CSSR" },
  { value: "8407", label: "Cuba" },
  { value: "8434", label: "Curacao" },
  { value: "8434", label: "Curacao Island" },
  { value: "2106", label: "Cymru" },
  { value: "3205", label: "Cyprus" },
  { value: "3302", label: "Czech" },
  { value: "3302", label: "Czech Republic" },
  { value: "3300", label: "Czechoslovakia" },
  { value: "9126", label: "Dakar" },
  { value: "3204", label: "Dalmatia" },
  { value: "4214", label: "Damascus" },
  { value: "7103", label: "Damoh" },
  { value: "2401", label: "Danmark" },
  { value: "3307", label: "Danzig" },
  { value: "2407", label: "Darlana" },
  { value: "1101", label: "Darnley Island" },
  { value: "1302", label: "Daru Island" },
  { value: "7103", label: "Delhi" },
  { value: "6202", label: "Democratic People's Republic of Korea" },
  { value: "2401", label: "Denmark" },
  { value: "9223", label: "Desroches Island" },
  { value: "2304", label: "Deutschland" },
  { value: "9205", label: "Djibouti" },
  { value: "3207", label: "Dodecanese Islands" },
  { value: "4212", label: "Doha" },
  { value: "8408", label: "Dominica" },
  { value: "8411", label: "Dominican Republic" },
  { value: "2201", label: "Donegal" },
  { value: "3207", label: "Drama" },
  { value: "2304", label: "Dresden" },
  { value: "4216", label: "Dubai" },
  { value: "2201", label: "Dublin" },
  { value: "5202", label: "Dutch East Indies" },
  { value: "8214", label: "Dutch Guiana" },
  { value: "5202", label: "Dutch Indies" },
  { value: "5202", label: "Dutch New Guinea" },
  { value: "8400", label: "Dutch West Indies" },
  { value: "9200", label: "East Africa" },
  { value: "0916", label: "East Asia" },
  { value: "2304", label: "East Germany" },
  { value: "5200", label: "East Indies" },
  { value: "7101", label: "East Pakistan" },
  { value: "5206", label: "East Timor" },
  { value: "8204", label: "Easter Island" },
  { value: "3300", label: "Eastern Europe" },
  { value: "8206", label: "Ecuador" },
  { value: "4102", label: "Egypt" },
  { value: "2201", label: "Eire" },
  { value: "8303", label: "El Salvador" },
  { value: "3207", label: "Elia" },
  { value: "1511", label: "Ellice Islands" },
  { value: "2102", label: "England" },
  { value: "3207", label: "Epirus" },
  { value: "9112", label: "Equatorial Guinea" },
  { value: "9206", label: "Eritrea" },
  { value: "3108", label: "Espana" },
  { value: "3303", label: "Estonia" },
  { value: "9207", label: "Ethiopia" },
  { value: "0911", label: "Europe" },
  { value: "8207", label: "Falkland Islands" },
  { value: "1402", label: "Fanning Island" },
  { value: "2402", label: "Faroe Islands" },
  { value: "7105", label: "Federal Democratic Republic of Nepal" },
  { value: "3200", label: "Federal Republic of Yugoslavia" },
  { value: "5203", label: "Federated Malay States" },
  { value: "1404", label: "Federated States of Micronesia" },
  { value: "1502", label: "Fiji" },
  { value: "1502", label: "Fiji Islands" },
  { value: "2403", label: "Finland" },
  { value: "3204", label: "Fiume" },
  { value: "1101", label: "Flinders Island" },
  { value: "3207", label: "Florina" },
  { value: "3200", label: "FLRJ" },
  { value: "3300", label: "Former Czechoslovakia" },
  { value: "0912", label: "Former USSR" },
  { value: "3206", label: "Former Yugoslav Republic of Macedonia (FYROM)" },
  { value: "3200", label: "Former Yugoslavia" },
  { value: "2303", label: "France" },
  { value: "2304", label: "Frankfurt" },
  { value: "9103", label: "French Cameroon" },
  { value: "9100", label: "French Central Africa" },
  { value: "8208", label: "French Guiana" },
  { value: "9116", label: "French Guinea" },
  { value: "1503", label: "French Polynesia" },
  { value: "9205", label: "French Somaliland" },
  { value: "9299", label: "French Southern Territories" },
  { value: "9121", label: "French Sudan" },
  { value: "1508", label: "Friendly Islands" },
  { value: "2308", label: "Friesland" },
  { value: "3206", label: "FYROM" },
  { value: "9113", label: "Gabon" },
  { value: "3000", label: "Galicia" },
  { value: "2201", label: "Galway" },
  { value: "9114", label: "Gambia" },
  { value: "4202", label: "Gaza Strip" },
  { value: "4202", label: "Gaza Strip and West Bank" },
  { value: "7204", label: "Georgia" },
  { value: "2304", label: "Gera" },
  { value: "2304", label: "Germany" },
  { value: "9115", label: "Ghana" },
  { value: "5105", label: "Gia Lai" },
  { value: "3102", label: "Gibraltar" },
  { value: "1402", label: "Gilbert Islands" },
  { value: "7103", label: "Goa" },
  { value: "1101", label: "Gold Coast" },
  { value: "3105", label: "Gozo Malta" },
  { value: "2100", label: "Great Britain" },
  { value: "3207", label: "Greece" },
  { value: "3207", label: "Greek Macedonia" },
  { value: "2404", label: "Greenland" },
  { value: "8412", label: "Grenada" },
  { value: "8424", label: "Grenadines" },
  { value: "2404", label: "Gronland" },
  { value: "1101", label: "Groote Eylandt" },
  { value: "8413", label: "Guadeloupe" },
  { value: "1401", label: "Guam" },
  { value: "6101", label: "Guangzhou" },
  { value: "8304", label: "Guatemala" },
  { value: "2107", label: "Guernsey" },
  { value: "9116", label: "Guinea" },
  { value: "9117", label: "Guinea-Bissau" },
  { value: "9116", label: "Guinee" },
  { value: "8211", label: "Guyana" },
  { value: "8208", label: "Guyane" },
  { value: "4205", label: "Haifa" },
  { value: "6101", label: "Hainan Island" },
  { value: "8414", label: "Haiti" },
  { value: "2304", label: "Halle" },
  { value: "2304", label: "Hamburg" },
  { value: "5105", label: "Hanoi" },
  { value: "2304", label: "Hanover" },
  { value: "7103", label: "Haryana" },
  { value: "8104", label: "Hawaii" },
  { value: "1199", label: "Heard Island" },
  { value: "2105", label: "Hebrides" },
  { value: "3202", label: "Hercegovina" },
  { value: "1501", label: "Hervey Island" },
  { value: "3202", label: "Herzegovina" },
  { value: "2304", label: "Hessen" },
  { value: "6102", label: "HK" },
  { value: "2308", label: "Holland" },
  { value: "3103", label: "Holy See" },
  { value: "8305", label: "Honduras" },
  { value: "6102", label: "Hong Kong" },
  { value: "6102", label: "Hong Kong (SAR of China)" },
  { value: "3204", label: "Hrvatska" },
  { value: "3304", label: "Hungary" },
  { value: "4215", label: "Icel" },
  { value: "2405", label: "Iceland" },
  { value: "0000", label: "Inadequately Described" },
  { value: "7103", label: "India" },
  { value: "5100", label: "Indo China" },
  { value: "5202", label: "Indonesia" },
  { value: "6101", label: "Inner Mongolia" },
  { value: "3207", label: "Ioannina" },
  { value: "3207", label: "Ionian Islands" },
  { value: "4203", label: "Iran" },
  { value: "4204", label: "Iraq" },
  { value: "2201", label: "Ireland" },
  { value: "5202", label: "Irian" },
  { value: "5202", label: "Irian Jaya" },
  { value: "2201", label: "Irish Free State" },
  { value: "2201", label: "Irish Republic" },
  { value: "2103", label: "Isle of Man" },
  { value: "2102", label: "Isle of Sheppey" },
  { value: "2102", label: "Isle of Wight" },
  { value: "2102", label: "Isles of Scilly" },
  { value: "4102", label: "Ismailia" },
  { value: "4205", label: "Israel" },
  { value: "4215", label: "Istanbul" },
  { value: "3200", label: "Istria" },
  { value: "3104", label: "Italia" },
  { value: "3104", label: "Italy" },
  { value: "9111", label: "Ivory Coast" },
  { value: "5202", label: "Jakarta" },
  { value: "8415", label: "Jamaica" },
  { value: "4105", label: "Jamhuryat es Sudan" },
  { value: "7103", label: "Jammu and Kashmir" },
  { value: "6201", label: "Japan" },
  { value: "6200", label: "Japan and the Koreas" },
  { value: "1599", label: "Jarvis Island" },
  { value: "5202", label: "Java" },
  { value: "2108", label: "Jersey" },
  { value: "4205", label: "Jerusalem" },
  { value: "1599", label: "Johnston and Sand Islands" },
  { value: "5203", label: "Johor" },
  { value: "5203", label: "Johore" },
  { value: "4206", label: "Jordan" },
  { value: "3200", label: "Jugoslavia" },
  { value: "3200", label: "Jugoslavija" },
  { value: "2404", label: "Kalaallit Nunaat" },
  { value: "5102", label: "Kampuchea" },
  { value: "1402", label: "Kanton Island" },
  { value: "4215", label: "Kars" },
  { value: "7100", label: "Kashmir" },
  { value: "3207", label: "Kastelorizo" },
  { value: "7205", label: "Kazakhstan" },
  { value: "7205", label: "Kazakstan" },
  { value: "3207", label: "Kefalonia" },
  { value: "9208", label: "Kenya" },
  { value: "7103", label: "Kerala" },
  { value: "4105", label: "Khartoum" },
  { value: "5102", label: "Khmer" },
  { value: "3205", label: "Kibris" },
  { value: "5105", label: "Kien Giang" },
  { value: "1101", label: "King Island" },
  { value: "1599", label: "Kingman Reef" },
  { value: "1402", label: "Kiribati" },
  { value: "5105", label: "Kon Tum" },
  { value: "4215", label: "Konya" },
  { value: "6203", label: "Korea" },
  { value: "6202", label: "Korea, Democratic People's Republic of (North)" },
  { value: "6203", label: "Korea, Republic of (South)" },
  { value: "3216", label: "Kosova" },
  { value: "3216", label: "Kosovo" },
  { value: "6102", label: "Kowloon" },
  { value: "5203", label: "Kuala Lumpur" },
  { value: "0915", label: "Kurdistan" },
  { value: "4215", label: "Kutahya" },
  { value: "4207", label: "Kuwait" },
  { value: "6101", label: "Kwang Chou Wan" },
  { value: "6101", label: "Kwantung" },
  { value: "3205", label: "Kypros" },
  { value: "7206", label: "Kyrgyz Republic" },
  { value: "7206", label: "Kyrgyzstan" },
  { value: "8102", label: "Labrador" },
  { value: "5203", label: "Labuan" },
  { value: "1400", label: "Ladrone Islands" },
  { value: "5105", label: "Lang Son" },
  { value: "5103", label: "Lao" },
  { value: "5103", label: "Laos" },
  { value: "2400", label: "Lapland" },
  { value: "3305", label: "Latvia" },
  { value: "3305", label: "Latvija" },
  { value: "4208", label: "Lebanon" },
  { value: "3207", label: "Lemnos" },
  { value: "9211", label: "Lesotho" },
  { value: "3305", label: "Lettland" },
  { value: "4200", label: "Levant" },
  { value: "2105", label: "Lewis" },
  { value: "9118", label: "Liberia" },
  { value: "4103", label: "Libiya" },
  { value: "4103", label: "Libya" },
  { value: "2305", label: "Liechtenstein" },
  { value: "1301", label: "Lifou Island" },
  { value: "3306", label: "Lithuania" },
  { value: "3104", label: "Lombardia" },
  { value: "3104", label: "Lombardy" },
  { value: "2104", label: "Londonderry" },
  { value: "8204", label: "Londonderry Island" },
  { value: "1101", label: "Lord Howe Island" },
  { value: "2303", label: "Lorraine" },
  { value: "2201", label: "Louth" },
  { value: "1301", label: "Loyalty Islands" },
  { value: "3104", label: "Lucania" },
  { value: "2306", label: "Luxembourg" },
  { value: "2306", label: "Luxemburg" },
  { value: "2405", label: "Lyoveldio Island" },
  { value: "3206", label: "Macadonia" },
  { value: "6103", label: "Macao" },
  { value: "6103", label: "Macau (SAR of China)" },
  { value: "3206", label: "Macedonia" },
  { value: "1101", label: "Macquarie Island" },
  { value: "9212", label: "Madagascar" },
  { value: "3106", label: "Madeira" },
  { value: "3207", label: "Magnesia" },
  { value: "3304", label: "Magyarorszag" },
  { value: "7103", label: "Mahe" },
  { value: "5100", label: "Mainland South-East Asia" },
  { value: "3108", label: "Majorca" },
  { value: "3206", label: "Makedhonia" },
  { value: "3206", label: "Makedonia" },
  { value: "3206", label: "Makedonija" },
  { value: "3206", label: "Makedoniya" },
  { value: "3206", label: "Makedonska" },
  { value: "5203", label: "Malacca" },
  { value: "9212", label: "Malagash" },
  { value: "1304", label: "Malakula" },
  { value: "4215", label: "Malatya" },
  { value: "9213", label: "Malawi" },
  { value: "5203", label: "Malaya" },
  { value: "5203", label: "Malaysia" },
  { value: "7104", label: "Maldives" },
  { value: "9121", label: "Mali" },
  { value: "3105", label: "Malta" },
  { value: "8207", label: "Malvinas" },
  { value: "6101", label: "Manchuria" },
  { value: "1501", label: "Mangaia Island" },
  { value: "4215", label: "Manisa" },
  { value: "8102", label: "Manitoba" },
  { value: "1302", label: "Manus" },
  { value: "4215", label: "Mardin" },
  { value: "1400", label: "Marianas Islands" },
  { value: "5200", label: "Maritime South-East Asia" },
  { value: "1503", label: "Marquesas Islands" },
  { value: "1403", label: "Marshall Islands" },
  { value: "8416", label: "Martinique" },
  { value: "1501", label: "Mauke Island" },
  { value: "9122", label: "Mauritania" },
  { value: "9214", label: "Mauritius" },
  { value: "9215", label: "Mayotte" },
  { value: "1199", label: "McDonald Islands" },
  { value: "2201", label: "Meath" },
  { value: "2304", label: "Mecklenburg" },
  { value: "1300", label: "Melanesia" },
  { value: "4108", label: "Melilla" },
  { value: "1101", label: "Melville Island" },
  { value: "3306", label: "Memelland" },
  { value: "4204", label: "Mesopotamia" },
  { value: "8306", label: "Mexico" },
  { value: "1400", label: "Micronesia" },
  { value: "1404", label: "Micronesia, Federated States of" },
  { value: "4200", label: "Middle East" },
  { value: "1599", label: "Midway Islands" },
  { value: "8103", label: "Miquelon" },
  { value: "4102", label: "Misr" },
  { value: "1501", label: "Mitiaro Island" },
  { value: "9216", label: "Mocambique" },
  { value: "3208", label: "Moldova" },
  { value: "5202", label: "Moluccas" },
  { value: "2307", label: "Monaco" },
  { value: "6104", label: "Mongolia" },
  { value: "2307", label: "Monte Carlo" },
  { value: "3214", label: "Montenegro" },
  { value: "8417", label: "Montserrat" },
  { value: "3302", label: "Morava" },
  { value: "3302", label: "Moravia" },
  { value: "4104", label: "Morocco" },
  { value: "9216", label: "Mozambique" },
  { value: "2201", label: "Munster" },
  { value: "1101", label: "Murray Island" },
  { value: "4211", label: "Muscat" },
  { value: "5101", label: "Myanmar" },
  { value: "2104", label: "N Ireland" },
  { value: "7103", label: "Nagaland" },
  { value: "9217", label: "Namibia" },
  { value: "9225", label: "Natal" },
  { value: "1405", label: "Nauru" },
  { value: "2308", label: "Nederland" },
  { value: "2308", label: "Nederlands" },
  { value: "8400", label: "Nederlandse Antillen" },
  { value: "7105", label: "Nepal" },
  { value: "7105", label: "Nepal, Federal Democratic Republic of" },
  { value: "2308", label: "Netherlands" },
  { value: "8400", label: "Netherlands Antilles" },
  { value: "5202", label: "Netherlands East Indies" },
  { value: "8400", label: "Netherlands West Indies" },
  { value: "8422", label: "Nevis" },
  { value: "1302", label: "New Britain" },
  { value: "8102", label: "New Brunswick" },
  { value: "1301", label: "New Caledonia" },
  { value: "1302", label: "New Guinea" },
  { value: "1304", label: "New Hebrides" },
  { value: "1302", label: "New Ireland" },
  { value: "1101", label: "New South Wales" },
  { value: "1201", label: "New Zealand" },
  { value: "8102", label: "Newfoundland" },
  { value: "8307", label: "Nicaragua" },
  { value: "7103", label: "Nicobar Islands" },
  { value: "9123", label: "Niger" },
  { value: "9124", label: "Nigeria" },
  { value: "6201", label: "Nihon" },
  { value: "6201", label: "Nippon" },
  { value: "1504", label: "Niue" },
  { value: "1302", label: "Niugini" },
  { value: "1102", label: "Norfolk Island" },
  { value: "2406", label: "Norge" },
  { value: "4100", label: "North Africa" },
  { value: "4000", label: "North Africa and the Middle East" },
  { value: "5203", label: "North Borneo" },
  { value: "6202", label: "North Korea" },
  { value: "4208", label: "North Lebanon" },
  { value: "5105", label: "North Viet Nam" },
  { value: "5105", label: "North Vietnam" },
  { value: "4217", label: "North Yemen" },
  { value: "6000", label: "North-East Asia" },
  { value: "8100", label: "Northern America" },
  { value: "3205", label: "Northern Cyprus" },
  { value: "2400", label: "Northern Europe" },
  { value: "2104", label: "Northern Ireland" },
  { value: "1406", label: "Northern Mariana Islands" },
  { value: "9231", label: "Northern Rhodesia" },
  { value: "1101", label: "Northern Territory" },
  { value: "2000", label: "North-West Europe" },
  { value: "8102", label: "Northwest Territories" },
  { value: "2406", label: "Norway" },
  { value: "1301", label: "Noumea" },
  { value: "8102", label: "Nova Scotia" },
  { value: "9213", label: "Nyasaland" },
  { value: "1201", label: "NZ" },
  { value: "1402", label: "Ocean Island" },
  { value: "1000", label: "Oceania and Antarctica" },
  { value: "6201", label: "Okinawa" },
  { value: "4211", label: "Oman" },
  { value: "8102", label: "Ontario" },
  { value: "9225", label: "Orange Free State" },
  { value: "4215", label: "Ordu" },
  { value: "7103", label: "Orissa" },
  { value: "2105", label: "Orkney Islands" },
  { value: "2301", label: "Osterreich" },
  { value: "6104", label: "Outer Mongolia" },
  { value: "1000", label: "Pacific Islands" },
  { value: "1400", label: "Pacific Islands Trust Territory" },
  { value: "5203", label: "Pahang" },
  { value: "7106", label: "Pakistan" },
  { value: "1407", label: "Palau" },
  { value: "5202", label: "Palembang" },
  { value: "4202", label: "Palestine" },
  { value: "1101", label: "Palm Island" },
  { value: "8308", label: "Panama" },
  { value: "1302", label: "Papua New Guinea" },
  { value: "1302", label: "Papua Niugini" },
  { value: "8212", label: "Paraguay" },
  { value: "2303", label: "Paris" },
  { value: "8200", label: "Patagonia" },
  { value: "3207", label: "Peloponnese" },
  { value: "3207", label: "Peloponnisos" },
  { value: "5203", label: "Penang" },
  { value: "4108", label: "Penon de Velez" },
  { value: "6101", label: "People's  Republic of China" },
  { value: "6202", label: "People's Democratic Republic of Korea" },
  { value: "5203", label: "Perak" },
  { value: "5203", label: "Perlis" },
  { value: "4203", label: "Persia" },
  { value: "8213", label: "Peru" },
  { value: "5204", label: "Philippines" },
  { value: "3207", label: "Phocis" },
  { value: "1402", label: "Phoenix Island" },
  { value: "3207", label: "Pieria" },
  { value: "5204", label: "Pilipinas" },
  { value: "3203", label: "Pirin Macedonia" },
  { value: "1513", label: "Pitcairn Island" },
  { value: "1513", label: "Pitcairn Islands" },
  { value: "1405", label: "Pleasant Island" },
  { value: "1302", label: "PNG" },
  { value: "3307", label: "Poland" },
  { value: "3312", label: "Polish Ukraine" },
  { value: "3307", label: "Polska" },
  { value: "1500", label: "Polynesia (excludes Hawaii)" },
  { value: "1599", label: "Polynesia (excludes Hawaii), nec" },
  { value: "1302", label: "Port Moresby" },
  { value: "4102", label: "Port Said" },
  { value: "3106", label: "Portugal" },
  { value: "9000", label: "Portuguese Africa" },
  { value: "9216", label: "Portuguese East Africa" },
  { value: "9117", label: "Portuguese Guinea" },
  { value: "6103", label: "Portuguese Macao" },
  { value: "5206", label: "Portuguese Timor" },
  { value: "9201", label: "Portuguese West Africa" },
  { value: "6101", label: "PR China" },
  { value: "6101", label: "PRC" },
  { value: "8102", label: "Prince Edward Island" },
  { value: "7103", label: "Puducherry" },
  { value: "8421", label: "Puerto Rico" },
  { value: "3104", label: "Puglia" },
  { value: "7100", label: "Punjab" },
  { value: "4212", label: "Qatar" },
  { value: "8102", label: "Quebec" },
  { value: "1606", label: "Queen Maud Land (Norway)" },
  { value: "1101", label: "Queensland" },
  { value: "1302", label: "Rabaul" },
  { value: "1501", label: "Rarotonga" },
  { value: "1101", label: "Rennel Island" },
  { value: "1303", label: "Rennell Island" },
  { value: "7202", label: "Republic of Armenia" },
  { value: "3301", label: "Republic of Belarus" },
  { value: "6101", label: "Republic of China" },
  { value: "9107", label: "Republic of Congo" },
  { value: "3303", label: "Republic of Estonia" },
  { value: "2201", label: "Republic of Ireland" },
  { value: "6203", label: "Republic of Korea" },
  { value: "3305", label: "Republic of Latvia" },
  { value: "3206", label: "Republic of Macedonia" },
  { value: "3208", label: "Republic of Moldova" },
  { value: "9225", label: "Republic of South Africa" },
  { value: "4111", label: "Republic of South Sudan" },
  { value: "7207", label: "Republic of Tajikstan" },
  { value: "3202", label: "Republika Srpska" },
  { value: "9218", label: "Reunion" },
  { value: "3207", label: "Rhodes" },
  { value: "9232", label: "Rhodesia" },
  { value: "4215", label: "Rize" },
  { value: "6105", label: "ROC Taiwan" },
  { value: "9214", label: "Rodrigues" },
  { value: "3211", label: "Romania" },
  { value: "1607", label: "Ross Dependency (New Zealand)" },
  { value: "1502", label: "Rotuma Island" },
  { value: "1502", label: "Rotumah Island" },
  { value: "3211", label: "Roumania" },
  { value: "9225", label: "RSA" },
  { value: "9221", label: "Ruanda" },
  { value: "3211", label: "Rumania" },
  { value: "3203", label: "Rumelia" },
  { value: "3308", label: "Russia" },
  { value: "3308", label: "Russian Federation" },
  { value: "9221", label: "Rwanda" },
  { value: "2304", label: "Saarland" },
  { value: "8433", label: "Saba" },
  { value: "5203", label: "Sabah" },
  { value: "3207", label: "Salonika" },
  { value: "1505", label: "Samoa" },
  { value: "1506", label: "Samoa, American" },
  { value: "3207", label: "Samos" },
  { value: "4215", label: "Samsun" },
  { value: "3107", label: "San Marino" },
  { value: "8104", label: "Sandwich Island" },
  { value: "1304", label: "Santo Island" },
  { value: "9125", label: "Sao Tome and Principe" },
  { value: "5203", label: "Saratok" },
  { value: "5203", label: "Sarawak" },
  { value: "3104", label: "Sardegna" },
  { value: "3104", label: "Sardinia" },
  { value: "2107", label: "Sark" },
  { value: "8102", label: "Saskatchewan" },
  { value: "4213", label: "Saudi Arabia" },
  { value: "1504", label: "Savage Island" },
  { value: "1505", label: "Savai'i" },
  { value: "2304", label: "Saxe Coburg Gotha" },
  { value: "2304", label: "Saxe Meiningen" },
  { value: "2400", label: "Scandinavia" },
  { value: "2311", label: "Schweiz" },
  { value: "2105", label: "Scotland" },
  { value: "5203", label: "Selangor" },
  { value: "9126", label: "Senegal" },
  { value: "3215", label: "Serbia" },
  { value: "3215", label: "Serbia Yugoslavia" },
  { value: "3200", label: "Serbia and Montenegro" },
  { value: "3207", label: "Serres" },
  { value: "9223", label: "Seychelles" },
  { value: "9223", label: "Seychelles Islands" },
  { value: "3200", label: "SFR Yugoslavia" },
  { value: "3200", label: "SFRJ" },
  { value: "6101", label: "Shanghai" },
  { value: "4216", label: "Sharjah" },
  { value: "2105", label: "Shetland Islands" },
  { value: "5104", label: "Siam" },
  { value: "3308", label: "Siberia" },
  { value: "3104", label: "Sicilia" },
  { value: "3104", label: "Sicily" },
  { value: "9127", label: "Sierra Leone" },
  { value: "7103", label: "Sikkim" },
  { value: "3307", label: "Silesia" },
  { value: "5205", label: "Singapore" },
  { value: "6100", label: "Sinitic Asia (includes Mongolia)" },
  { value: "8433", label: "Sint Eustatius" },
  { value: "8435", label: "Sint Maarten (Dutch part)" },
  { value: "3206", label: "Skopje" },
  { value: "3206", label: "Slav Macedonia" },
  { value: "3204", label: "Slavania" },
  { value: "3204", label: "Slavonia" },
  { value: "3311", label: "Slovak Republic" },
  { value: "3311", label: "Slovakia" },
  { value: "3212", label: "Slovania" },
  { value: "3212", label: "Slovanija" },
  { value: "3212", label: "Slovenia" },
  { value: "3212", label: "Slovenija" },
  { value: "3311", label: "Slovenska Republika" },
  { value: "4215", label: "Smyrna" },
  { value: "1303", label: "Solomon Islands" },
  { value: "9224", label: "Somalia" },
  { value: "9224", label: "Somaliland" },
  { value: "9224", label: "Somaliya" },
  { value: "5105", label: "Son La" },
  { value: "9225", label: "South Africa" },
  { value: "8200", label: "South America" },
  { value: "8299", label: "South America, nec" },
  { value: "1101", label: "South Australia" },
  { value: "3200", label: "South Eastern Europe" },
  { value: "8299", label: "South Georgia" },
  { value: "7103", label: "South India" },
  { value: "6203", label: "South Korea" },
  { value: "8299", label: "South Sandwich Islands" },
  { value: "4111", label: "South Sudan, Republic of" },
  { value: "4111", label: "South Sudan" },
  { value: "5105", label: "South Viet Nam" },
  { value: "5105", label: "South Vietnam" },
  { value: "2106", label: "South Wales" },
  { value: "9217", label: "South West Africa" },
  { value: "4217", label: "South Yemen" },
  { value: "5000", label: "South-East Asia" },
  { value: "7000", label: "Southern and Central Asia" },
  { value: "9200", label: "Southern and East Africa" },
  { value: "9299", label: "Southern and East Africa, nec" },
  { value: "3000", label: "Southern and Eastern Europe" },
  { value: "7100", label: "Southern Asia" },
  { value: "3100", label: "Southern Europe" },
  { value: "2201", label: "Southern Ireland" },
  { value: "9232", label: "Southern Rhodesia" },
  { value: "3108", label: "Spain" },
  { value: "9112", label: "Spanish Guinea" },
  { value: "4108", label: "Spanish North Africa" },
  { value: "4107", label: "Spanish Sahara" },
  { value: "3215", label: "Srbija" },
  { value: "7107", label: "Sri Lanka" },
  { value: "3312", label: "SS Ukraina" },
  { value: "8431", label: "St Barthelemy" },
  { value: "8433", label: "St Eustatius" },
  { value: "9222", label: "St Helena" },
  { value: "9222", label: "St Helena, Ascension and Tristan da Cunha" },
  { value: "8422", label: "St Kitts" },
  { value: "8422", label: "St Kitts and Nevis" },
  { value: "8423", label: "St Lucia" },
  { value: "8432", label: "St Martin (French part)" },
  { value: "8103", label: "St Pierre" },
  { value: "8103", label: "St Pierre and Miquelon" },
  { value: "8428", label: "St Thomas" },
  { value: "8424", label: "St Vincent" },
  { value: "8424", label: "St Vincent and the Grenadines" },
  { value: "1201", label: "Stewart Island" },
  { value: "1101", label: "Stradbroke Island" },
  { value: "5200", label: "Straits Settlements" },
  { value: "9000", label: "Sub-Saharan Africa" },
  { value: "4105", label: "Sudan" },
  { value: "4102", label: "Suez" },
  { value: "2304", label: "Suhl" },
  { value: "5202", label: "Sulawesi" },
  { value: "5202", label: "Sumatra" },
  { value: "5200", label: "Sunda Islands" },
  { value: "2403", label: "Suomi" },
  { value: "5202", label: "Surabaya" },
  { value: "8214", label: "Surinam" },
  { value: "8214", label: "Suriname" },
  { value: "9226", label: "Swaziland" },
  { value: "2407", label: "Sweden" },
  { value: "2311", label: "Switzerland" },
  { value: "4214", label: "Syria" },
  { value: "7207", label: "Tadjikistan" },
  { value: "7207", label: "Tadzhikistan" },
  { value: "1302", label: "Tagula Island" },
  { value: "1503", label: "Tahiti" },
  { value: "6105", label: "Taiwan" },
  { value: "7207", label: "Tajikistan" },
  { value: "7107", label: "Tamil Eelam" },
  { value: "7103", label: "Tamil Nadu" },
  { value: "9227", label: "Tanganyika" },
  { value: "1304", label: "Tanna" },
  { value: "9227", label: "Tanzania" },
  { value: "1402", label: "Tarawa Island" },
  { value: "1101", label: "Tas" },
  { value: "1101", label: "Tasmania" },
  { value: "3300", label: "Tchecoslovakia" },
  { value: "5104", label: "Thailand" },
  { value: "3206", label: "The former Yugoslav Republic of Macedonia" },
  { value: "3207", label: "Thessalonika" },
  { value: "3207", label: "Thessaloniki" },
  { value: "3200", label: "Thrace" },
  { value: "1101", label: "Thursday Island" },
  { value: "6101", label: "Tibet" },
  { value: "5206", label: "Timor" },
  { value: "5206", label: "Timor-Leste" },
  { value: "8425", label: "Tobago" },
  { value: "1304", label: "Toga" },
  { value: "9128", label: "Togo" },
  { value: "1507", label: "Tokelau" },
  { value: "1508", label: "Tonga" },
  { value: "1508", label: "Tongatapu" },
  { value: "5105", label: "Tonkin" },
  { value: "1101", label: "Torres Strait Islands" },
  { value: "8427", label: "Tortola" },
  { value: "7200", label: "Transcaucasia" },
  { value: "3211", label: "Transilvania" },
  { value: "4206", label: "Transjordan" },
  { value: "9225", label: "Transkei" },
  { value: "9225", label: "Transvaal" },
  { value: "3211", label: "Transylvania" },
  { value: "3104", label: "Trieste" },
  { value: "3207", label: "Trikala" },
  { value: "8425", label: "Trinidad" },
  { value: "8425", label: "Trinidad and Tobago" },
  { value: "4103", label: "Tripoli" },
  { value: "9222", label: "Tristan da Cunha" },
  { value: "1302", label: "Trobriand Islands" },
  { value: "3302", label: "Tschechien" },
  { value: "1503", label: "Tuamotus" },
  { value: "4215", label: "Tunceli" },
  { value: "4106", label: "Tunisia" },
  { value: "4106", label: "Tunisie" },
  { value: "7200", label: "Turkestan" },
  { value: "4215", label: "Turkey" },
  { value: "7208", label: "Turkmen" },
  { value: "7208", label: "Turkmenistan" },
  { value: "8426", label: "Turks and Caicos Islands" },
  { value: "3104", label: "Tuscany" },
  { value: "1511", label: "Tuvalu" },
  { value: "4216", label: "UAE" },
  { value: "9228", label: "Uganda" },
  { value: "2100", label: "UK" },
  { value: "8427", label: "UK Virgin Islands" },
  { value: "3312", label: "Ukraina" },
  { value: "3312", label: "Ukraine" },
  { value: "3312", label: "Ukraine USSR" },
  { value: "2104", label: "Ulster" },
  { value: "4211", label: "Uman" },
  { value: "3104", label: "Umbria" },
  { value: "4216", label: "Umm Al Quwain" },
  { value: "4216", label: "United Arab Emirates" },
  { value: "4000", label: "United Arab States" },
  { value: "2100", label: "United Kingdom" },
  { value: "8427", label: "United Kingdom Virgin Islands" },
  { value: "2100", label: "United Kingdom, Channel Islands and Isle of Man" },
  { value: "8104", label: "United States" },
  { value: "8104", label: "United States of America" },
  { value: "8428", label: "United States Virgin Islands" },
  { value: "0000", label: "Unknown" },
  { value: "9121", label: "Upper Senegal" },
  { value: "9102", label: "Upper Volta" },
  { value: "8215", label: "Uruguay" },
  { value: "9203", label: "Urundi" },
  { value: "8104", label: "US" },
  { value: "8428", label: "US Virgin Islands" },
  { value: "8104", label: "USA" },
  { value: "4215", label: "Usak" },
  { value: "0912", label: "USSR" },
  { value: "7103", label: "Uttar Pradesh" },
  { value: "7211", label: "Uzbek" },
  { value: "7211", label: "Uzbekistan" },
  { value: "3104", label: "Valle d'Aosta" },
  { value: "1304", label: "Vanuatu" },
  { value: "3103", label: "Vatican City" },
  { value: "1508", label: "Vava'u" },
  { value: "8216", label: "Venezuela" },
  { value: "8216", label: "Venezuela, Bolivarian Republic of" },
  { value: "1101", label: "Vic" },
  { value: "1101", label: "Victoria" },
  { value: "2301", label: "Vienna" },
  { value: "5105", label: "Viet Nam" },
  { value: "5105", label: "Vietnam" },
  { value: "8427", label: "Virgin Islands, British" },
  { value: "8428", label: "Virgin Islands, United States" },
  { value: "9102", label: "Volta" },
  { value: "1101", label: "WA" },
  { value: "1599", label: "Wake Island" },
  { value: "2106", label: "Wales" },
  { value: "1512", label: "Wallis and Futuna" },
  { value: "1402", label: "Washington Island" },
  { value: "2201", label: "Waterford" },
  { value: "1101", label: "Wednesday Island" },
  { value: "4202", label: "West Bank" },
  { value: "7103", label: "West Bengal" },
  { value: "2304", label: "West Berlin" },
  { value: "2304", label: "West Germany" },
  { value: "8400", label: "West Indies" },
  { value: "5202", label: "West Irian" },
  { value: "5203", label: "West Malaysia" },
  { value: "5202", label: "West Papua" },
  { value: "5202", label: "West Timor" },
  { value: "1101", label: "Western Australia" },
  { value: "2300", label: "Western Europe" },
  { value: "4107", label: "Western Sahara" },
  { value: "1505", label: "Western Samoa" },
  { value: "3301", label: "White Russia" },
  { value: "2304", label: "Wurttemberg" },
  { value: "1101", label: "Xmas Island" },
  { value: "7103", label: "Yanam" },
  { value: "7103", label: "Yanaon" },
  { value: "5101", label: "Yangon" },
  { value: "3207", label: "Yannina" },
  { value: "4217", label: "Yemen" },
  { value: "3200", label: "Yugoslavia" },
  { value: "3202", label: "Yugoslavia Bosnia" },
  { value: "3204", label: "Yugoslavia Croatia" },
  { value: "3206", label: "Yugoslavia Macedonia" },
  { value: "3215", label: "Yugoslavia Serbia" },
  { value: "3200", label: "Yugoslavia, Federal Republic of" },
  { value: "3200", label: "Yugoslavija" },
  { value: "8102", label: "Yukon" },
  { value: "9108", label: "Zaire" },
  { value: "9231", label: "Zambia" },
  { value: "9227", label: "Zanzibar" },
  { value: "9232", label: "Zimbabwe" },
  { value: "@@@@", label: "Not specified" }
];
