export interface AsclOption {
  value: string;
  label: string;
}

// Generated from ABS ASCL coding index (Australian Standard Classification of Languages)
// Value = 4-digit AVETMISS Language Identifier code
export const asclOptions: AsclOption[] = [
  { value: '1201', label: 'English' },
  { value: '@@@@', label: 'Not specified' },
  { value: '8000', label: 'Aboriginal' },
  { value: '8998', label: 'Aboriginal Australian' },
  { value: '8924', label: 'Aboriginal Kreol' },
  { value: '2101', label: 'Acadian' },
  { value: '6513', label: 'Acehnese' },
  { value: '4206', label: 'Acerian' },
  { value: '9201', label: 'Acholi' },
  { value: '8901', label: 'Adnyamathanha' },
  { value: '2201', label: 'Aegean' },
  { value: '4000', label: 'Afghan' },
  { value: '9202', label: 'Afrikaans' },
  { value: '9299', label: 'Afro-Asiatic' },
  { value: '9203', label: 'Akan' },
  { value: '3201', label: 'Albanian' },
  { value: '8903', label: 'Alyawarr' },
  { value: '9204', label: 'Amharic' },
  { value: '8904', label: 'Anmatyerr' },
  { value: '4202', label: 'Arabic' },
  { value: '4203', label: 'Aramaic' },
  { value: '3202', label: 'Armenian' },
  { value: '4204', label: 'Assyrian Neo-Aramaic' },
  { value: '7101', label: 'Assamese' },
  { value: '6401', label: 'Balinese' },
  { value: '3501', label: 'Basque' },
  { value: '7102', label: 'Bengali' },
  { value: '9205', label: 'Bemba' },
  { value: '5201', label: 'Bislama' },
  { value: '3203', label: 'Bosnian' },
  { value: '3204', label: 'Bulgarian' },
  { value: '5101', label: 'Burmese' },
  { value: '6101', label: 'Cantonese' },
  { value: '3205', label: 'Catalan' },
  { value: '6501', label: 'Cebuano' },
  { value: '4205', label: 'Chaldean Neo-Aramaic' },
  { value: '5102', label: 'Khmer' },
  { value: '6100', label: 'Chinese' },
  { value: '3301', label: 'Croatian' },
  { value: '3101', label: 'Czech' },
  { value: '2401', label: 'Danish' },
  { value: '4201', label: 'Dari' },
  { value: '9206', label: 'Dinka' },
  { value: '2301', label: 'Dutch' },
  { value: '2302', label: 'Frisian' },
  { value: '1501', label: 'Fijian' },
  { value: '2402', label: 'Finnish' },
  { value: '2101', label: 'French' },
  { value: '9207', label: 'Fulfulde' },
  { value: '1301', label: 'Gaelic' },
  { value: '3502', label: 'Galician' },
  { value: '3206', label: 'Georgian' },
  { value: '2201', label: 'German' },
  { value: '3207', label: 'Greek' },
  { value: '7103', label: 'Gujarati' },
  { value: '6103', label: 'Hakka' },
  { value: '9208', label: 'Hausa' },
  { value: '4207', label: 'Hebrew' },
  { value: '7104', label: 'Hindi' },
  { value: '3102', label: 'Hungarian' },
  { value: '6502', label: 'Ilocano' },
  { value: '6504', label: 'Indonesian' },
  { value: '2102', label: 'Italian' },
  { value: '6201', label: 'Japanese' },
  { value: '6402', label: 'Javanese' },
  { value: '7105', label: 'Kannada' },
  { value: '5103', label: 'Karen' },
  { value: '7106', label: 'Kashmiri' },
  { value: '5104', label: 'Khasi' },
  { value: '6301', label: 'Korean' },
  { value: '4101', label: 'Kurdish' },
  { value: '5105', label: 'Lao' },
  { value: '2103', label: 'Latin' },
  { value: '3401', label: 'Latvian' },
  { value: '3402', label: 'Lithuanian' },
  { value: '3208', label: 'Macedonian' },
  { value: '9211', label: 'Malagasy' },
  { value: '6505', label: 'Malay' },
  { value: '7107', label: 'Malayalam' },
  { value: '4208', label: 'Maltese' },
  { value: '6102', label: 'Mandarin' },
  { value: '1202', label: 'Maori' },
  { value: '7108', label: 'Marathi' },
  { value: '6500', label: 'Filipino' },
  { value: '6105', label: 'Min Nan' },
  { value: '6106', label: 'Teochew' },
  { value: '6104', label: 'Hokkien' },
  { value: '1401', label: 'Motu' },
  { value: '7111', label: 'Nepali' },
  { value: '2403', label: 'Norwegian' },
  { value: '7112', label: 'Oriya' },
  { value: '9212', label: 'Oromo' },
  { value: '4102', label: 'Pashto' },
  { value: '4103', label: 'Persian' },
  { value: '8925', label: 'Kriol' },
  { value: '8926', label: 'Torres Strait Creole' },
  { value: '8900', label: 'Australian Indigenous Languages' },
  { value: '8902', label: 'Pitjantjatjara' },
  { value: '8938', label: 'Warlpiri' },
  { value: '8942', label: 'Yolngu Matha' },
  { value: '3103', label: 'Polish' },
  { value: '3211', label: 'Portuguese' },
  { value: '7113', label: 'Punjabi' },
  { value: '3212', label: 'Romanian' },
  { value: '3213', label: 'Romany' },
  { value: '3403', label: 'Russian' },
  { value: '1502', label: 'Samoan' },
  { value: '7114', label: 'Sanskrit' },
  { value: '3302', label: 'Serbian' },
  { value: '9213', label: 'Shona' },
  { value: '7115', label: 'Sindhi' },
  { value: '7116', label: 'Sinhalese' },
  { value: '3104', label: 'Slovak' },
  { value: '3303', label: 'Slovenian' },
  { value: '9214', label: 'Somali' },
  { value: '3214', label: 'Spanish' },
  { value: '9215', label: 'Swahili' },
  { value: '2404', label: 'Swedish' },
  { value: '6508', label: 'Tagalog' },
  { value: '7117', label: 'Tamil' },
  { value: '7118', label: 'Telugu' },
  { value: '5106', label: 'Thai' },
  { value: '6107', label: 'Tibetan' },
  { value: '9216', label: 'Tigrinya' },
  { value: '1503', label: 'Tongan' },
  { value: '4211', label: 'Turkish' },
  { value: '3404', label: 'Ukrainian' },
  { value: '7121', label: 'Urdu' },
  { value: '6403', label: 'Sundanese' },
  { value: '5107', label: 'Vietnamese' },
  { value: '2104', label: 'Walloon' },
  { value: '2105', label: 'Welsh' },
  { value: '9217', label: 'Yoruba' },
  { value: '9218', label: 'Zulu' }
];
