export interface SaccOption {
  value: string;
  label: string;
}

// Generated from ABS SACC coding index (Standard Australian Classification of Countries)
// Value = 4-digit AVETMISS Country Identifier code
export const saccOptions: SaccOption[] = [
  { value: '1101', label: 'Australia' },
  { value: '@@@@', label: 'Not specified' },
  { value: '4216', label: 'Abu Dhabi' },
  { value: '3207', label: 'Acarnania' },
  { value: '5202', label: 'Aceh' },
  { value: '4215', label: 'Adana' },
  { value: '1601', label: 'Adelie Land (France)' },
  { value: '4217', label: 'Aden' },
  { value: '7201', label: 'Afghanistan' },
  { value: '0918', label: 'Africa' },
  { value: '3204', label: 'Agram' },
  { value: '1501', label: 'Aitutaki Island' },
  { value: '2408', label: 'Aland Islands' },
  { value: '8104', label: 'Alaska' },
  { value: '3201', label: 'Albania' },
  { value: '8102', label: 'Alberta' },
  { value: '2107', label: 'Alderney' },
  { value: '4214', label: 'Aleppo' },
  { value: '4102', label: 'Alexandria' },
  { value: '4101', label: 'Algeria' },
  { value: '4108', label: 'Alhucemas' },
  { value: '5202', label: 'Ambon' },
  { value: '8104', label: 'America' },
  { value: '1506', label: 'American Samoa' },
  { value: '8000', label: 'Americas' },
  { value: '4214', label: 'Anatolia' },
  { value: '3203', label: 'Andorra' },
  { value: '9201', label: 'Angola' },
  { value: '1401', label: 'Anguilla' },
  { value: '4215', label: 'Ankara' },
  { value: '1402', label: 'Antigua and Barbuda' },
  { value: '8201', label: 'Argentina' },
  { value: '3205', label: 'Armenia' },
  { value: '1403', label: 'Aruba' },
  { value: '1507', label: 'Ashmore and Cartier Islands' },
  { value: '7101', label: 'Asia' },
  { value: '1502', label: 'Austral Islands' },
  { value: '2301', label: 'Austria' },
  { value: '3206', label: 'Azerbaijan' },
  { value: '1404', label: 'Bahamas' },
  { value: '4201', label: 'Bahrain' },
  { value: '5202', label: 'Bali' },
  { value: '7202', label: 'Bangladesh' },
  { value: '1405', label: 'Barbados' },
  { value: '2302', label: 'Bavaria' },
  { value: '2201', label: 'Belarus' },
  { value: '2303', label: 'Belgium' },
  { value: '8301', label: 'Belize' },
  { value: '9101', label: 'Benin' },
  { value: '8101', label: 'Bermuda' },
  { value: '7203', label: 'Bhutan' },
  { value: '8202', label: 'Bolivia' },
  { value: '3202', label: 'Bosnia and Herzegovina' },
  { value: '9202', label: 'Botswana' },
  { value: '1503', label: 'Bougainville' },
  { value: '8203', label: 'Brazil' },
  { value: '8102', label: 'British Columbia' },
  { value: '1406', label: 'British Virgin Islands' },
  { value: '5201', label: 'Brunei Darussalam' },
  { value: '3207', label: 'Bulgaria' },
  { value: '9102', label: 'Burkina Faso' },
  { value: '5101', label: 'Myanmar' },
  { value: '9203', label: 'Burundi' },
  { value: '5102', label: 'Cambodia' },
  { value: '9103', label: 'Cameroon' },
  { value: '8102', label: 'Canada' },
  { value: '9104', label: 'Cape Verde' },
  { value: '1407', label: 'Cayman Islands' },
  { value: '9105', label: 'Central African Republic' },
  { value: '9106', label: 'Chad' },
  { value: '2107', label: 'Channel Islands' },
  { value: '8204', label: 'Chile' },
  { value: '6101', label: 'China' },
  { value: '1507', label: 'Coral Sea Islands' },
  { value: '8205', label: 'Colombia' },
  { value: '9204', label: 'Comoros' },
  { value: '9205', label: 'Congo' },
  { value: '1504', label: 'Cook Islands' },
  { value: '8302', label: 'Costa Rica' },
  { value: '9107', label: 'Cote d\'Ivoire' },
  { value: '3204', label: 'Croatia' },
  { value: '1408', label: 'Cuba' },
  { value: '1403', label: 'Curacao' },
  { value: '3213', label: 'Cyprus' },
  { value: '3208', label: 'Czech Republic' },
  { value: '2401', label: 'Denmark' },
  { value: '9206', label: 'Djibouti' },
  { value: '1411', label: 'Dominica' },
  { value: '1412', label: 'Dominican Republic' },
  { value: '5202', label: 'East Timor' },
  { value: '8206', label: 'Ecuador' },
  { value: '4102', label: 'Egypt' },
  { value: '8303', label: 'El Salvador' },
  { value: '2100', label: 'England' },
  { value: '9108', label: 'Equatorial Guinea' },
  { value: '9207', label: 'Eritrea' },
  { value: '2402', label: 'Estonia' },
  { value: '9208', label: 'Ethiopia' },
  { value: '2000', label: 'Europe' },
  { value: '8207', label: 'Falkland Islands' },
  { value: '2403', label: 'Faroe Islands' },
  { value: '1301', label: 'Fiji' },
  { value: '2404', label: 'Finland' },
  { value: '2102', label: 'France' },
  { value: '8208', label: 'French Guiana' },
  { value: '1502', label: 'French Polynesia' },
  { value: '9111', label: 'Gabon' },
  { value: '9112', label: 'Gambia' },
  { value: '3205', label: 'Georgia' },
  { value: '2302', label: 'Germany' },
  { value: '9113', label: 'Ghana' },
  { value: '2106', label: 'Gibraltar' },
  { value: '3207', label: 'Greece' },
  { value: '2405', label: 'Greenland' },
  { value: '1413', label: 'Grenada' },
  { value: '1414', label: 'Guadeloupe' },
  { value: '1506', label: 'Guam' },
  { value: '8304', label: 'Guatemala' },
  { value: '2107', label: 'Guernsey' },
  { value: '9114', label: 'Guinea' },
  { value: '9115', label: 'Guinea-Bissau' },
  { value: '8209', label: 'Guyana' },
  { value: '1415', label: 'Haiti' },
  { value: '8305', label: 'Honduras' },
  { value: '6102', label: 'Hong Kong' },
  { value: '3208', label: 'Hungary' },
  { value: '2406', label: 'Iceland' },
  { value: '7102', label: 'India' },
  { value: '5202', label: 'Indonesia' },
  { value: '4203', label: 'Iran' },
  { value: '4204', label: 'Iraq' },
  { value: '2103', label: 'Ireland' },
  { value: '2107', label: 'Isle of Man' },
  { value: '4205', label: 'Israel' },
  { value: '3207', label: 'Italy' },
  { value: '1416', label: 'Jamaica' },
  { value: '6201', label: 'Japan' },
  { value: '2107', label: 'Jersey' },
  { value: '4206', label: 'Jordan' },
  { value: '7103', label: 'Kazakhstan' },
  { value: '9211', label: 'Kenya' },
  { value: '1505', label: 'Kiribati' },
  { value: '6104', label: 'North Korea' },
  { value: '6105', label: 'South Korea' },
  { value: '4207', label: 'Kuwait' },
  { value: '7104', label: 'Kyrgyzstan' },
  { value: '5103', label: 'Laos' },
  { value: '2407', label: 'Latvia' },
  { value: '4208', label: 'Lebanon' },
  { value: '9212', label: 'Lesotho' },
  { value: '9116', label: 'Liberia' },
  { value: '4103', label: 'Libya' },
  { value: '2304', label: 'Liechtenstein' },
  { value: '2408', label: 'Lithuania' },
  { value: '2305', label: 'Luxembourg' },
  { value: '6103', label: 'Macau' },
  { value: '3207', label: 'Macedonia' },
  { value: '9213', label: 'Madagascar' },
  { value: '9214', label: 'Malawi' },
  { value: '5203', label: 'Malaysia' },
  { value: '7204', label: 'Maldives' },
  { value: '9117', label: 'Mali' },
  { value: '3211', label: 'Malta' },
  { value: '1506', label: 'Marshall Islands' },
  { value: '1417', label: 'Martinique' },
  { value: '9118', label: 'Mauritania' },
  { value: '9215', label: 'Mauritius' },
  { value: '9216', label: 'Mayotte' },
  { value: '8103', label: 'Mexico' },
  { value: '1506', label: 'Micronesia' },
  { value: '2202', label: 'Moldova' },
  { value: '2306', label: 'Monaco' },
  { value: '6106', label: 'Mongolia' },
  { value: '3212', label: 'Montenegro' },
  { value: '1418', label: 'Montserrat' },
  { value: '4104', label: 'Morocco' },
  { value: '9217', label: 'Mozambique' },
  { value: '9218', label: 'Namibia' },
  { value: '1507', label: 'Nauru' },
  { value: '7205', label: 'Nepal' },
  { value: '2307', label: 'Netherlands' },
  { value: '1302', label: 'New Caledonia' },
  { value: '1201', label: 'New Zealand' },
  { value: '8306', label: 'Nicaragua' },
  { value: '9121', label: 'Niger' },
  { value: '9122', label: 'Nigeria' },
  { value: '1504', label: 'Niue' },
  { value: '1506', label: 'Northern Mariana Islands' },
  { value: '2411', label: 'Norway' },
  { value: '4211', label: 'Oman' },
  { value: '7206', label: 'Pakistan' },
  { value: '1506', label: 'Palau' },
  { value: '4205', label: 'Palestine' },
  { value: '8307', label: 'Panama' },
  { value: '1503', label: 'Papua New Guinea' },
  { value: '8211', label: 'Paraguay' },
  { value: '8212', label: 'Peru' },
  { value: '5204', label: 'Philippines' },
  { value: '1504', label: 'Pitcairn Islands' },
  { value: '3213', label: 'Poland' },
  { value: '3214', label: 'Portugal' },
  { value: '1421', label: 'Puerto Rico' },
  { value: '4212', label: 'Qatar' },
  { value: '9218', label: 'Reunion' },
  { value: '3215', label: 'Romania' },
  { value: '2203', label: 'Russian Federation' },
  { value: '9221', label: 'Rwanda' },
  { value: '1502', label: 'Samoa' },
  { value: '3216', label: 'San Marino' },
  { value: '9123', label: 'Sao Tome and Principe' },
  { value: '4213', label: 'Saudi Arabia' },
  { value: '2104', label: 'Scotland' },
  { value: '9124', label: 'Senegal' },
  { value: '3212', label: 'Serbia' },
  { value: '9222', label: 'Seychelles' },
  { value: '9125', label: 'Sierra Leone' },
  { value: '5205', label: 'Singapore' },
  { value: '3208', label: 'Slovakia' },
  { value: '3204', label: 'Slovenia' },
  { value: '1508', label: 'Solomon Islands' },
  { value: '9223', label: 'Somalia' },
  { value: '9224', label: 'South Africa' },
  { value: '3217', label: 'Spain' },
  { value: '7207', label: 'Sri Lanka' },
  { value: '4105', label: 'Sudan' },
  { value: '8213', label: 'Suriname' },
  { value: '9225', label: 'Swaziland' },
  { value: '2412', label: 'Sweden' },
  { value: '2308', label: 'Switzerland' },
  { value: '4214', label: 'Syria' },
  { value: '6107', label: 'Taiwan' },
  { value: '7105', label: 'Tajikistan' },
  { value: '9226', label: 'Tanzania' },
  { value: '5104', label: 'Thailand' },
  { value: '9126', label: 'Togo' },
  { value: '1504', label: 'Tokelau' },
  { value: '1511', label: 'Tonga' },
  { value: '1422', label: 'Trinidad and Tobago' },
  { value: '4106', label: 'Tunisia' },
  { value: '4215', label: 'Turkey' },
  { value: '7106', label: 'Turkmenistan' },
  { value: '1423', label: 'Turks and Caicos Islands' },
  { value: '1512', label: 'Tuvalu' },
  { value: '9227', label: 'Uganda' },
  { value: '2204', label: 'Ukraine' },
  { value: '4216', label: 'United Arab Emirates' },
  { value: '2100', label: 'United Kingdom' },
  { value: '8104', label: 'United States of America' },
  { value: '8214', label: 'Uruguay' },
  { value: '7107', label: 'Uzbekistan' },
  { value: '1513', label: 'Vanuatu' },
  { value: '3218', label: 'Vatican City' },
  { value: '8215', label: 'Venezuela' },
  { value: '5105', label: 'Vietnam' },
  { value: '2105', label: 'Wales' },
  { value: '1514', label: 'Wallis and Futuna' },
  { value: '4107', label: 'Western Sahara' },
  { value: '4217', label: 'Yemen' },
  { value: '9228', label: 'Zambia' },
  { value: '9232', label: 'Zimbabwe' }
];
